### ISSUE TITLE
Windows packaging: DTEF Template missing

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple#108]
annnnd now i get this error
```
Traceback (most recent call last):
  File "module/dungeon_graphics/controller/tileset.py", line 197, in on_btn_export_clicked
  File "shutil.py", line 415, in copy
  File "shutil.py", line 261, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\SkyTemple\\skytemple_dtef\\template.png'
```

---
Beep, boop, I'm [a bot](https://github.com/Parakoopa/IssueBot)! This issue was created by `@Theory_of_Everything` in `#sprite-asset-help`.

**Comment by Parakoopa** [comment]
> Also, this template has a problem; it seems that the image was shifted 1 pixel to the left as there is a 1px column of transparent pixels on the right side
