### ISSUE TITLE
Gtk3 error on manjaro linux

### ISSUE THREAD

**Issue by zazbone** [SkyTemple/skytemple#155]
Hi,
I tried to install skytemple using the command:
`pip install --upgrade skytemple[eventserver,discord]`
On python 3.9 first, then with python 3.7
But the same issue happens when i tried to start the app
`ValueError: Namespace GtkSource not available for version 3.0`

The full backtrace look like python fail to find gtk3 lib or binding:
```shell
Traceback (most recent call last):
  File "/home/zazbone/.local/bin/skytemple", line 5, in <module>
    from skytemple.main import main
  File "/home/zazbone/.local/lib/python3.7/site-packages/skytemple/main.py", line 30, in <module>
    from skytemple_ssb_debugger.main import get_debugger_data_dir
  File "/home/zazbone/.local/lib/python3.7/site-packages/skytemple_ssb_debugger/main.py", line 29, in <module>
    from skytemple_ssb_debugger.controller.main import MainController
  File "/home/zazbone/.local/lib/python3.7/site-packages/skytemple_ssb_debugger/controller/main.py", line 32, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/home/zazbone/.local/lib/python3.7/site-packages/gi/__init__.py", line 130, in require_version
    (namespace, version))
ValueError: Namespace GtkSource not available for version 3.0

```
`gtk3` and `python-gobject` are installed with pacman on my system

PS: I had to install manualy install `typing_extensions`, seem like it not referencent in requirements
`ModuleNotFoundError: No module named 'typing_extensions'`

May another python dep is missing for gtk ?

Thanks !

**Comment by Parakoopa** [comment]
Hi, you need to install `gtksourceview3` from pacman.

**Comment by zazbone** [comment]
Ok nice, it's actually working 
Thanks and good luck ^^
