### ISSUE TITLE
error when trying to apply ASM patch

### ISSUE THREAD

**Issue by Lonsfor** [SkyTemple/skytemple#265]
when i try to apply a patch it prints this error in the terminal
```
2021-05-17 17:21:05,310 - system - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/skytemple_files/patch/arm_patcher.py", line 58, in apply
    shutil.copytree(patch_file_dir, tmp, dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/skytemple/module/patch/controller/main.py", line 97, in on_btn_apply_clicked
    self._patcher.apply(patch)
  File "/usr/lib/python3.7/site-packages/skytemple_files/patch/patches.py", line 137, in apply
    self._rom, self._config
  File "/usr/lib/python3.7/site-packages/skytemple_files/patch/handler/move_shortcuts.py", line 65, in apply
    apply()
  File "/usr/lib/python3.7/site-packages/skytemple_files/patch/patches.py", line 146, in _apply_armips
    stub_path_for_version, self._config.game_edition)
  File "/usr/lib/python3.7/site-packages/skytemple_files/patch/arm_patcher.py", line 187, in apply
    raise RuntimeError(f(_("Error while applying the patch: {ex}"))) from ex
UnboundLocalError: local variable 'f' referenced before assignment
```

skytemple 1.2.3

Python 3.7.10

armips v0.11.0

**Comment by irdkwia** [comment]
According to the docs argument "dirs_exist_ok" does not exist for shutil.copytree prior to python 3.8, so you would need to upgrade your python version

**Comment by Parakoopa** [comment]
Hm, still gonna keep this open, because I do want 3.7 support.

**Comment by theCapypara** [comment]
3.7 is no longer supported by SkyTemple, so this is obsolete.
