### ISSUE TITLE
Monster 0 is not editable (in beta)

### ISSUE THREAD

**Issue by Parakoopa** [SkyTemple/skytemple#38]
Trying to edit monster 0 raises this error:
```
Traceback (most recent call last):
  File "skytemple/controller/main.py", line 378, in on_view_loaded
  File "skytemple/module/monster/controller/monster.py", line 80, in get_view
  File "skytemple/module/monster/controller/monster.py", line 542, in _check_sprite_size
  File "site-packages/skytemple_files/container/bin_pack/model.py", line 62, in __getitem__
IndexError: list index out of range
```

**Comment by Parakoopa** [comment]
This seems to be fixed.
