### ISSUE TITLE
RuntimeError: Error while applying the patch: [Errno 13] Permission denied: 'armips'

### ISSUE THREAD

**Issue by Gabbinetto** [SkyTemple/skytemple#451]
If I try to apply a ASM patch the application crashes and it gives a long error. This is the whole output from the software:
```
gabriele@LAPTOP-GABBO:~$ skytemple
Failed setting up Python locale.
[Errno 2] No translation file found for domain: 'skytemple'
2022-08-20 22:14:44,791 - skytemple_files.dungeon_data.mappa_bin.item_list - WARNING - MappaItemCategory is deprecated. Use Pmd2DungeonData's item_categories attribute instead. This deprecated class will provide dynamically generated values from the default EU XML configuration.

(skytemple:20495): Gtk-CRITICAL **: 22:14:45.417: gtk_assistant_set_page_has_padding: assertion 'child != NULL' failed
2022-08-20 22:14:46,293 - root - WARNING - Error setting up Discord integration:
Traceback (most recent call last):
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple/main.py", line 178, in run_main
    discord_listener = DiscordPresence()
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple/core/events/impl/discord.py", line 57, in __init__
    self.rpc = Presence(CLIENT_ID)
  File "/home/gabriele/.local/lib/python3.10/site-packages/pypresence/presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/gabriele/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 28, in __init__
    raise DiscordNotFound
pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.

(skytemple:20495): Gtk-WARNING **: 22:15:55.934: Child name 'main' not found in GtkStack

(skytemple:20495): Gtk-WARNING **: 22:15:57.353: Child name 'main' not found in GtkStack

(skytemple:20495): Gtk-WARNING **: 22:16:15.912: Child name 'main' not found in GtkStack

(skytemple:20495): Gtk-WARNING **: 22:16:27.338: Child name 'main' not found in GtkStack

(skytemple:20495): Gtk-WARNING **: 22:16:36.809: Child name 'main' not found in GtkStack

(skytemple:20495): Gtk-WARNING **: 22:16:40.942: Child name 'main' not found in GtkStack
2022-08-20 22:17:03,911 - skytemple.controller.main - INFO - Loaded ROM /home/gabriele/Desktop/4468 - Pokemon Mystery Dungeon - Explorers of Sky (Europe) (En,Fr,De,Es,It).nds (EoS_EU)
2022-08-20 22:17:11,590 - skytemple.core.error_handler - ERROR - Error applying the patch:
Error while applying the patch: [Errno 13] Permission denied: 'armips'
Traceback (most recent call last):
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple_files/patch/arm_patcher.py", line 140, in apply
    result = subprocess.Popen(cmd_line,
  File "/home/gabriele/.local/lib/python3.10/site-packages/sentry_sdk/integrations/stdlib.py", line 198, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'armips'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple/module/patch/controller/main.py", line 117, in on_btn_apply_clicked
    self._apply(patch)
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple/module/patch/controller/main.py", line 243, in _apply
    self._patcher.apply(patch, parameter_data)
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple_files/patch/patches.py", line 201, in apply
    patch.apply(
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple_files/patch/handler/extra_space.py", line 74, in apply
    apply()
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple_files/patch/patches.py", line 212, in _apply_armips
    self._arm_patcher.apply(patch, self._config.binaries,
  File "/home/gabriele/.local/lib/python3.10/site-packages/skytemple_files/patch/arm_patcher.py", line 186, in apply
    raise RuntimeError(f(_("Error while applying the patch: {ex}"))) from ex
RuntimeError: Error while applying the patch: [Errno 13] Permission denied: 'armips'
```

I have armips compiled in `/usr/local/bin/armips`, the executable is specifically in the `build` folder. Also added it to PATH.
I used `chmod` on the executable too. I don't know what this permission is.

**Comment by marius851000** [comment]
Have you checked that armips run in the terminal, that is, that you can execute ``armips --help`` ?

**Comment by Gabbinetto** [comment]
> Have you checked that armips run in the terminal, that is, that you can execute `armips --help` ?

Actually not, it doesn't find the command. Still kinda new to Linux sorry. What should I do?

**Comment by theCapypara** [comment]
Hi, did you install armips?
If so, you need to add it to your system's PATH variable, this is the variable where your system looks for executables. The easiest way to do this is just to move the armips binary to `/usr/local/bin`. You also need to make sure it's marked as executable by setting the executable bit on the binary, this can be done eg. by doing `chmod +x path/to/armips`

**Comment by Gabbinetto** [comment]
> Hi, did you install armips? If so, you need to add it to your system's PATH variable, this is the variable where your system looks for executables. The easiest way to do this is just to move the armips binary to `/usr/local/bin`. You also need to make sure it's marked as executable by setting the executable bit on the binary, this can be done eg. by doing `chmod +x path/to/armips`

Thanks it worked. I tried adding it to PATH but apparently I did it wrong. Thanks!
