### ISSUE TITLE
ImportError when running SkyTemple

### ISSUE THREAD

**Issue by End45** [SkyTemple/skytemple#492]
Multiple people have reported getting an exception when trying to launch SkyTemple 1.4.5 on Windows.
```
Traceback (most recent call last):
  File "main.py", line 107, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "core/events/manager.py", line 23, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "core/events/abstract_listener.py", line 22, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "core/rom_project.py", line 37, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "core/sprite_provider.py", line 39, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "skytemple_files/common/types/file_types.py", line 98, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "skytemple_files/script/ssb/handler.py", line 36, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "skytemple_files/script/ssb/model.py", line 32, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "explorerscript/ssb_converting/ssb_decompiler.py", line 27, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "explorerscript/ssb_converting/decompiler/label_jump_to_resolver.py", line 31, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "explorerscript/ssb_converting/ssb_special_ops.py", line 30, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "igraph/__init__.py", line 34, in <module>
ImportError: DLL load failed while importing _igraph: The specified module could not be found.
```
Seems like it affects the randomizer too.
I tried reproducing the issue myself, but it works fine for me, so not sure of what the problem could be.

**Comment by End45** [comment]
Update: There's been 5 reports in the Discord server in less than 24 hours, seems like it's a pretty common issue.

**Comment by theCapypara** [comment]
Does it work under macOS?
